#ifndef _SLAZYLIST_CODES_H_
#define _SLAZYLIST_CODES_H_

#define SLAZYLIST_OK 0
#define SLAZYLIST_FAILED_ALLOC 1
#define SLAZYLIST_INVALID_NODE 2
#define SLAZYLIST_IS_EMPTY 3
#define SLAZYLIST_INDEX_OUT_OF_BOUNDS 4

#endif